version: '3.7'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  frontend:
    build:
      context: ./frontend
      target: 'develop-stage'
    environment:
      - UPSTREAM=http://localhost:4000
    ports:
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - ./frontend:/app:rw,cached

  api:
    build:
      context: ./api
      target: 'develop-stage'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=api
    depends_on:
      - db
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
    volumes:
      - ./api:/app:rw,cached

